server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=booking_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

inventory:
  service:
    url: http://localhost:8081

logging:
  level:
    root: INFO
    com.cineverse.booking: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: CineVerse Inventory Service
    version: 1.0.0
    description: Movie ticket inventory and seat-hold service