server:
  port: 8081

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=catalog_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Change to validate when using Flyway later
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE